#!/bin/sh

# TODO: take first argument, search the corresponding mes_{}.json (ex: linMono)
# TODO: difficulty arrise in the last argument : *_results_$r.json, unfortunately
# TODO: the last argument must be chosen (because the last file is actually the more recent )


pb_id=$1

cat examples/mes_"$pb_id".json | build/mainstdin $pb_id && ./graph_publish.py *_results_"$pb_id".json
